### ISSUE TITLE
InSight mission dictionary has been updated but files are not being generated automatically

### ISSUE THREAD

**Issue by sslavney** [pds-data-dictionaries/ldd-insight#1]
Yesterday I uploaded a new version of the InSight mission dictionary ingest file in the branch rev-210608. I thought the schema file and other dictionary files would be generated automatically, as they are for other dictionaries, but nothing has happened. What should I do to make this new version public?

**Comment by jordanpadams** [comment]
@sslavney the insight LDD repo looks like it was created before the new automated processes were created, so the repo will need to be retrofitted. https://pds-data-dictionaries.github.io/development/ldd-create.html#retrofit-existing-ldd-repository-admin-stewards-only . unfortunately it is not super straightforward to do it this way...

one workaround could be to rename this repo to something else (ldd-insight-legacy), and create a new fresh ldd-insight repo with your ingest LDD file added

**Comment by sslavney** [comment]
I'll do whatever is easiest for you, Jordan. This might be the last time the InSight dictionary needs to be updated.

**Comment by jordanpadams** [comment]
i just updated quickly. https://github.com/pds-data-dictionaries/ldd-insight/tree/rev-210608/build/development/ab1860e545a99d8e3651b929e3fcfaad2a9f17a5/1.11.0.0 . if you would like to build against additional pds4 versions, you can add to the pds4_versions.txt in the repo
